apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 540670137645.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 540670137645.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 938e0547
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
